[package]
name = "marco-pad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"

[profile.release]
strip = true
opt-level = "s"
lto = "fat"
codegen-units = 1